import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "@/store/store";
import { ReduxProvider } from "./ReduxProvider";
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Research Ustad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body suppressHydrationWarning className={roboto.className}>
          <div>
            <Toaster />
            {children}
          </div>
        </body>
      </ReduxProvider>
    </html>
  );
}
